---

- name: Refresh remote "local facts" for glory
  setup:
    filter: ansible_local

- name: Gather apptest facts to dict to prepare for output
  set_fact:
    _tbb_selenium_dict:
      hidserv_token: "{{ ansible_local.tor_app.hidserv_token }}"
      journalist_location: "{{ ansible_local.tor_app.journalist_location  }}"
      source_location: "{{ ansible_local.tor_app.source_location  }}"
      sleep_time: "{{ tbb_sleep_time }}"
      user:
        name: "{{ tbb_selenium_user }}"
        password: "{{ tbb_selenium_password }}"
        secret: "{{ tbb_selenium_secret }}"

- name: Dump facts to local json for in-take
  copy:
    content: "{{ _tbb_selenium_dict | to_nice_json }}"
    dest: "{{ tbb_funcfolder }}"
  become: no
  delegate_to: localhost
