---
- include: staging_wsgi_files.yml
  when: "'staging' in group_names"
  tags:
    - apache

- include: apparmor_complain.yml
  when: securedrop_app_test_apparmor_complain
  tags:
    - aa-complain

- include: modern_gettext.yml

- import_tasks: extract_apptor_test_config.yml
  tags:
    - functional_test
